apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: demo
resources:
  - ../../base
images:
  - name: fastapi-app
    newName: docker.io/jaga9989/simple-python-app
    newTag: 1a926625198772daee65dd809d4680a906601461
replicas:
  - name: fastapi-app
    count: 1
