apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: demo
resources:
  - ../../base
images:
  - name: fastapi-app
    newName: docker.io/jaga9989/simple-python-app
    newTag: 332953a9a70a4c9a48896b8e51e6338dd36ea464
replicas:
  - name: fastapi-app
    count: 1
